#!/usr/bin/env python
'''
Autogenerated code using arya.py
Original Object Document Input: 
<?xml version="1.0" encoding="UTF-8"?><imdata totalCount="1"><infraAccPortP annotation="" descr="" dn="uni/infra/accportprof-Heroes_server1" name="Heroes_server1" nameAlias="" ownerKey="" ownerTag="" userdom=":all:"><infraHPortS annotation="" descr="" name="ethernet1_21" nameAlias="" ownerKey="" ownerTag="" type="range" userdom=":all:"><infraRsAccBaseGrp annotation="" fexId="101" tDn="uni/infra/funcprof/accportgrp-Heroes_standard_access" userdom=":all:"/><infraPortBlk annotation="" descr="" fromCard="1" fromPort="21" name="block2" nameAlias="" toCard="1" toPort="21" userdom=":all:"/></infraHPortS></infraAccPortP></imdata>

raise RuntimeError('Please review the auto generated code before ' +
                    'executing the output. Some placeholders will ' +
                    'need to be changed')
'''
# list of packages that should be imported for this code to work
import cobra.mit.access
import cobra.mit.request
import cobra.mit.session
import cobra.model.infra
import cobra.model.pol
from cobra.internal.codec.xmlcodec import toXMLStr
import urllib3
import csv

urllib3.disable_warnings()

def read_csv():
    results = []
    with open('CUSTOMER-XXX-interface-profile.csv', newline='') as csvfile:
        reader = csv.reader(csvfile, delimiter=',')
        for row in reader:
            results.append(row)
    # re move header
    return results[1:] 
    
# main
def main(host, user, password):

    # log into an APIC and create a directory object
    ls = cobra.mit.session.LoginSession('https://' + host, user, password)
    md = cobra.mit.access.MoDirectory(ls)
    md.login()

    # the top level object on which operations will be made
    polUni = cobra.model.pol.Uni('')
    infraInfra = cobra.model.infra.Infra(polUni)
    
    resultList = read_csv()
    
     # Create infra access port profile by the number of rows
    for lst in resultList: 
        # last column (type) - fex or not division
        ptype = lst[11]

        infraAccPortP = None
        if ptype.lower() == "fex":
            infraAccPortP = cobra.model.infra.FexP(infraInfra, ownerKey='', name=lst[0], descr=lst[1], ownerTag='')
        else:
            infraAccPortP = cobra.model.infra.AccPortP(infraInfra, ownerKey='', name=lst[0], descr=lst[1], ownerTag='')
    
        # build the request using cobra syntax
        
        infraHPortS = cobra.model.infra.HPortS(infraAccPortP,annotation='', ownerKey='', type='range', name=lst[2], descr=lst[3], ownerTag='', userdom=':all:')
        infraRsAccBaseGrp = cobra.model.infra.RsAccBaseGrp(infraHPortS, annotation='', fexId='101', tDn= 'uni/infra/funcprof/accportgrp-'+ lst[4], userdom=':all:')
        infraPortBlk = cobra.model.infra.PortBlk(infraHPortS, annotation='',descr=lst[9], fromCard=lst[5], fromPort=lst[6], name='block1',toCard=lst[7], toPort=lst[8], userdom=':all:')

        # commit the generated code to APIC
        #print(toXMLStr(infraInfra))
        c = cobra.mit.request.ConfigRequest()
        c.addMo(infraInfra)
        md.commit(c)

if __name__ == '__main__':
    from argparse import ArgumentParser
    parser = ArgumentParser("Create Leaf Interface Profile")
    parser.add_argument('-d', '--host', help='APIC host name or IP', required=True)
    parser.add_argument('-u', '--user', help='user name', required=True)
    parser.add_argument('-p', '--password', help='user password', required=True)
    args = parser.parse_args()

    main(args.host, args.user, args.password)

