apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-ro
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","roles"]
  verbs: ["get", "watch", "list"]